### ISSUE TITLE
plagiarism?

### ISSUE THREAD

**Issue by futuristudios** [alexsosn/SwiftMLBook#1]
hey there, i was looking to purchase book on ml/ai for/in swift when i came across your book. i also came across this [book](https://smile.amazon.co.uk/Leverage-Learning-Programming-Intelligent-Applications/dp/B0B6XN1TG8/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1663058458&sr=1-1) supposedly published ([?](https://isbnsearch.org/isbn/9798842094073)) a few months ago whose contents appear to be word for word a copy of yours. just thought i’d let you know just in case it hadn’t come to your attention yet.

**Comment by alexsosn** [comment]
Dear @futuristudios thanks for letting me know. It's funny, they even left all my personal details in there, just replacing the name. Originally Packt published an unfinished draft of my book and messed up the pictures and formulas. I assume that's what they still sell. They added a second co-author on the Amazon who never contributed anything to the book. And there's an (unlicensed?) [Chinese translation of the book](https://www.amazon.com/Swift-Machine-Learning-Practical-Chinese/dp/711166499X) out there. Most importantly Packt didn't pay me monthly royalties as per the contract, so TBH I couldn't care less if people download the book for free from libgen or elsewhere.
